import os, glob

files = glob.glob('/Users/anshul/Documents/Arushi/PPT/site/public/*.html')

old_css = """        /* Light Mode Overrides generated by Stitch Design Loop */
        html.light {
            filter: invert(1) hue-rotate(180deg);
        }
        html.light img, html.light video {
            filter: invert(1) hue-rotate(180deg);
        }
        html.light .mesh-gradient {
            opacity: 0.6;
        }
        html.light .glow-button {
            box-shadow: 0 4px 15px rgba(0, 238, 255, 0.5);
        }
    </style>"""

new_css = """        /* Light Mode Overrides generated by Stitch Design Loop */
        html.light body, html.light .bg-background-dark, html.light .bg-\\[\\#0a0f16\\] { background-color: #f8fafc !important; }
        html.light .text-white, html.light .text-slate-100 { color: #0f172a !important; }
        html.light .text-slate-300, html.light .text-slate-400, html.light .text-slate-500, html.light .text-\\[\\#8e9bb0\\] { color: #475569 !important; }
        html.light .bg-white\\/5, html.light .glass, html.light .glass-card { background: rgba(255,255,255,0.85) !important; border-color: rgba(0,0,0,0.1) !important; box-shadow: 0 4px 20px -2px rgba(0,0,0,0.05) !important; }
        html.light .border-white\\/10 { border-color: rgba(0,0,0,0.15) !important; }
        html.light .mesh-gradient { filter: invert(0.9) hue-rotate(180deg); opacity: 0.3 !important; }
        html.light .grid-pattern { background-image: linear-gradient(rgba(0,0,0,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(0,0,0,0.05) 1px, transparent 1px) !important; }
        html.light .bg-primary { color: #0f172a !important; }
        html.light .bg-black\\/20, html.light .bg-white\\/10 { background-color: rgba(0,0,0,0.05) !important; }
        html.light .glow-button { box-shadow: 0 4px 15px rgba(0, 238, 255, 0.5) !important; }
        html.light #appAlertModal > div, html.light #appConfirmModal > div, html.light #appPromptModal > div { background: rgba(255,255,255,0.9) !important; border-color: rgba(0,0,0,0.1) !important; }
    </style>"""

for f in files:
    with open(f, 'r') as file:
        content = file.read()
    if old_css in content:
        content = content.replace(old_css, new_css)
        with open(f, 'w') as file:
            file.write(content)
        print(f"Updated {f}")
